log:
  level: info

runner:
  file: .runner
  capacity: 1
  envs: {}
  env_file: ""
  timeout: 3h
  shutdown_timeout: 5m
  insecure: false
  labels: []
  allocate_pty: false

cache:
  enabled: false

container:
  network: ""
  network_create_options:
    enable_ipv4: true
    enable_ipv6: false
  privileged: false
  options: ""
  valid_volumes: []
  docker_host: unix:///run/user/1000/docker.sock
  force_pull: false
  force_rebuild: false
  require_docker: true
  docker_timeout: 30s
  bind_workdir: false

host:
  workdir_parent: ""

metrics:
  enabled: false
  addr: 127.0.0.1:9101
