[Definition]
failregex = ^.*Failed authentication attempt from <HOST>(?::\d+)?(?:\s|$)
            ^.*Failed authentication attempt for .* from <HOST>(?::\d+)?: .*$
            ^.*Failed authentication attempt \(cannot find repository: .*\) from <HOST>(?::\d+)?(?:\s|$)
            ^.*Failed authentication attempt for .* with key .* \(not authorized to .*\) from <HOST>(?::\d+)?(?:\s|$)
ignoreregex =
